Update build mac script (#105)
* Test build ghost mac

* Update dependencies

* Update building script

* Add || when installing fluxclient & beamify

* Add echo

* Test intel only

* Add CAIROCFFI_DLL_DIRECTORIES

* Add ln -s

* Add DYLD_LIBRARY_PATH

* Update DYLD_LIBRARY_PATH

* Fix

* Update script

* Update mac yml

* Remove debug echo

diff --git a/.github/workflows/buildghost-mac.yml b/.github/workflows/buildghost-mac.yml
--- a/.github/workflows/buildghost-mac.yml
+++ b/.github/workflows/buildghost-mac.yml
@@ -12,7 +12,7 @@ jobs:
     strategy:
       matrix:
         python-version: [3.8]
-        os: [macOS-13]
+        os: [macOS-15, macOS-15-intel]
 
     steps:
       - uses: actions/checkout@v4
@@ -23,8 +23,11 @@ jobs:
 
       - name: Install Brew Packages
         run: |
-          # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
           brew install zlib
+
+      - name: Set dyld path for cairo
+        run: |
+          echo "DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}$(brew --prefix cairo)/lib" >> $GITHUB_ENV
 
       - name: Install Python dependencies
         run: |
@@ -44,7 +47,7 @@ jobs:
         run: |
           cd .github/actions/beamify/python
           # FIXME: Failed to install deps only on github action, use || operator temporary
-          python3 setup.py install --verbose
+          python3 setup.py install --verbose || echo "Failed to install beamify"
 
       - name: Install Fluxsvg
         uses: flux3dp/fluxsvg@2.7.7
@@ -53,7 +56,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: flux3dp/fluxclient-dev
-          ref: 2.9.6
+          ref: 2.9.8
           token: ${{ secrets.REPO_TOKEN }}
           path: .github/actions/fluxclient
 
@@ -61,7 +64,7 @@ jobs:
         run: |
           cd .github/actions/fluxclient
           # FIXME: Failed to install deps only on github action, use || operator temporary
-          python3 setup.py install --verbose
+          python3 setup.py install --verbose || echo "Failed to install beamify"
 
       - name: Build Flux Api
         run: |
